spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gbswschoolpaper?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: schoolPaper
    password: schoolPaper3657!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 3000